name: Next.js CI/CD
on:
  push:
    branches:
      - main      # Deploy to production on push to main
  pull_request:
    branches:
      - main      # Run preview deployments on PRs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run tests (if any)
      - name: Run tests
        run: npm test || echo "No tests found"

      # 5. Build Next.js frontend
      - name: Build Next.js
        run: npm run build

      # 6. Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .    # root of your project
          vercel-args: "--prod"   # remove "--prod" for PR previews
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
